/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea;

import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author jose
 */
public class interfaz extends javax.swing.JFrame {
String cpu = "",pantalla="", ram="",garantia="", precio="";
    int dato,gar;
    double pant,cRam, pre; 
    
     
    public interfaz() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jblcpu = new javax.swing.JLabel();
        jbltamaño = new javax.swing.JLabel();
        lblram = new javax.swing.JLabel();
        jblgarantia = new javax.swing.JLabel();
        jblprecio = new javax.swing.JLabel();
        jblmarca = new javax.swing.JLabel();
        jblcamara = new javax.swing.JLabel();
        jtfgarantia = new javax.swing.JTextField();
        jtfram = new javax.swing.JTextField();
        jtfpantalla = new javax.swing.JTextField();
        jcmbmarca = new javax.swing.JComboBox<>();
        jcbprincipal = new javax.swing.JCheckBox();
        jcbsecundaria = new javax.swing.JCheckBox();
        jcbflash = new javax.swing.JCheckBox();
        jbldescCam = new javax.swing.JLabel();
        btnejecutar = new javax.swing.JButton();
        jtfnum = new javax.swing.JTextField();
        jtfprecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtexapant = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtpix = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        jTextField7.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jblcpu.setText("cpu numero de nucleos");

        jbltamaño.setText("tamaño de pantalla");

        lblram.setText("cantidad de RAM");

        jblgarantia.setText("Tiempo de garantia");

        jblprecio.setText("precio");

        jblmarca.setText("marca");

        jblcamara.setText("Camara");

        jtfgarantia.setBackground(new java.awt.Color(255, 255, 255));
        jtfgarantia.setForeground(new java.awt.Color(0, 0, 0));
        jtfgarantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfgarantiaKeyTyped(evt);
            }
        });

        jtfram.setBackground(new java.awt.Color(255, 255, 255));
        jtfram.setForeground(new java.awt.Color(0, 0, 0));
        jtfram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtframActionPerformed(evt);
            }
        });
        jtfram.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtframKeyTyped(evt);
            }
        });

        jtfpantalla.setBackground(new java.awt.Color(255, 255, 255));
        jtfpantalla.setForeground(new java.awt.Color(0, 0, 0));
        jtfpantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfpantallaKeyTyped(evt);
            }
        });

        jcmbmarca.setBackground(new java.awt.Color(255, 255, 255));
        jcmbmarca.setForeground(new java.awt.Color(0, 0, 0));
        jcmbmarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEXUS", "PIXIE", "LENOVO", "HUAWEI", "SONY", "APPLE", "SAMSUNG", "ALCATEL", "LG", "OTRA" }));

        jcbprincipal.setText("Principal");

        jcbsecundaria.setText("secundaria");

        jcbflash.setText("flash");

        btnejecutar.setText("Ejecutar");
        btnejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejecutarActionPerformed(evt);
            }
        });

        jtfnum.setBackground(new java.awt.Color(255, 255, 255));
        jtfnum.setForeground(new java.awt.Color(0, 0, 0));
        jtfnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfnumKeyTyped(evt);
            }
        });

        jtfprecio.setBackground(new java.awt.Color(255, 255, 255));
        jtfprecio.setForeground(new java.awt.Color(0, 0, 0));
        jtfprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfprecioKeyTyped(evt);
            }
        });

        jtexapant.setColumns(20);
        jtexapant.setRows(5);
        jScrollPane1.setViewportView(jtexapant);

        jLabel1.setText("Megapixeles");

        jScrollPane2.setViewportView(jtxtpix);

        jLabel2.setText("PUNTAJE DE MOVILES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jblcamara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbldescCam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbprincipal)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnejecutar)
                                    .addComponent(jcbsecundaria, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addComponent(jcbflash))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jblprecio)
                                    .addComponent(jblgarantia)
                                    .addComponent(lblram)
                                    .addComponent(jbltamaño)
                                    .addComponent(jblcpu))
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jblmarca)
                                .addGap(108, 108, 108)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfgarantia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jtfram, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jtfpantalla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jtfnum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfprecio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcmbmarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblcpu)
                    .addComponent(jtfnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbltamaño)
                    .addComponent(jtfpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblram)
                    .addComponent(jtfram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblgarantia)
                    .addComponent(jtfgarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblprecio)
                    .addComponent(jtfprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblmarca)
                    .addComponent(jcmbmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblcamara)
                    .addComponent(jcbsecundaria)
                    .addComponent(jcbflash)
                    .addComponent(jcbprincipal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbldescCam)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnejecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtframActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtframActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtframActionPerformed

    private void jtfnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfnumKeyTyped
     char letra= evt.getKeyChar();
     
       cpu=cpu +letra;
       dato=Integer.parseInt(cpu);
       if(dato>12){
           JOptionPane.showMessageDialog(null, "el rango de ingreso debe ser menor o igual a 12");
           jtfnum.setText(null);
           evt.consume();
           dato=0;
           cpu="";
       }
       if(letra<'0' || letra>'9'){
           evt.consume();
       }
       
        int limite=2;
        if(jtfnum.getText().length()==limite){
            evt.consume();
        }
        
    }//GEN-LAST:event_jtfnumKeyTyped

    private void jtfpantallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfpantallaKeyTyped
       char letra=evt.getKeyChar();
         
         pantalla=pantalla+letra;
        pant=Double.parseDouble(pantalla);
        
        if(pant<3.0 || pant>6.7){
            JOptionPane.showMessageDialog(null,"NO se permiten valores mayores a 6.7 ni menores a 3.0");
            jtfpantalla.setText(null);
            evt.consume();
            pant=0;
            pantalla="";
        }
         
         if((letra<'0' || letra>'9') && letra!='.'){
            evt.consume();

        }
         int limite=3;
        if(jtfpantalla.getText().length()==limite){
            evt.consume();
            
        }
    }//GEN-LAST:event_jtfpantallaKeyTyped

    private void jtframKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtframKeyTyped
        char letra=evt.getKeyChar();
         
         ram=ram+letra;
        cRam=Double.parseDouble(ram);
         if((letra<'0' || letra>'9') && letra!='.'){
            evt.consume();
             }
         if(cRam<0.5 || cRam>6.0){
            JOptionPane.showMessageDialog(null,"Los valores deben estar en el rango de a 0.5  a 6.0");
            jtfram.setText(null);
            evt.consume();
            cRam=0;
            ram="";
        }
            int limite=3;
        if(jtfram.getText().length()==limite){
            evt.consume();
        }
        
      
    }//GEN-LAST:event_jtframKeyTyped

    private void jtfgarantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfgarantiaKeyTyped
       char letra=evt.getKeyChar();

        if(letra<'0' || letra>'9'){
            
            evt.consume();
            
        }
       garantia=garantia+letra;
        gar=Integer.parseInt(garantia);
        if(gar>24){
            JOptionPane.showMessageDialog(null,"Numero invalido, la garantia no excede a 24 meses");
            jtfgarantia.setText(null);
            evt.consume();
            gar=0;
            garantia="";
        }
        
       
         int limite=2;
        if(jtfgarantia.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_jtfgarantiaKeyTyped

    private void jtfprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfprecioKeyTyped
        char letra=evt.getKeyChar();
         
         precio=precio+letra;
        pre=Double.parseDouble(precio);
         if((letra<'0' || letra>'9') && letra!='.'){
            evt.consume();

        }
         int limite=6;
        if(jtfprecio.getText().length()==limite){
            evt.consume();
        }
        
        if(pre<0.01 || pre>999.99){
            JOptionPane.showMessageDialog(null,"Valor fuera de rango \n. Rango (mayor a 0.01 y menor o igual a 999.99 )");
            jtfprecio.setText(null);
            evt.consume();
            pre=0;
            precio="";
        }    
    }//GEN-LAST:event_jtfprecioKeyTyped

    private void btnejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejecutarActionPerformed
       String camara="";
        if(jcbprincipal.isSelected()){
           
        }
        if(jcbsecundaria.isSelected()){
            camara=camara+"secundaria";
        }
        if(jcbflash.isSelected()){
            
    }//GEN-LAST:event_btnejecutarActionPerformed
    jtexapant.setText("El movil posee "+cpu+" "+"Nucleos"+"\nEl tamaño de su pantalla es: "+pant+" "+"Pulgadas"+
               "\nCon una memoria ram de"+" "+cRam+" "+"GB"+"\nGarantia de:"+" "+jtfgarantia.getText()+" "+"meses"+"\nSu precio es de $ "+jtfprecio.getText()+"\nMarca"+" "+jcmbmarca.getSelectedItem()+"\nCon una camara"+" "+jcbprincipal.getText()+" "+camara+" "+" "+jtxtpix.getText()+" "+"MegaPixeles"+" "); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new interfaz().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnejecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel jblcamara;
    private javax.swing.JLabel jblcpu;
    private javax.swing.JLabel jbldescCam;
    private javax.swing.JLabel jblgarantia;
    private javax.swing.JLabel jblmarca;
    private javax.swing.JLabel jblprecio;
    private javax.swing.JLabel jbltamaño;
    private javax.swing.JCheckBox jcbflash;
    private javax.swing.JCheckBox jcbprincipal;
    private javax.swing.JCheckBox jcbsecundaria;
    private javax.swing.JComboBox<String> jcmbmarca;
    private javax.swing.JTextArea jtexapant;
    private javax.swing.JTextField jtfgarantia;
    private javax.swing.JTextField jtfnum;
    private javax.swing.JTextField jtfpantalla;
    private javax.swing.JTextField jtfprecio;
    private javax.swing.JTextField jtfram;
    private javax.swing.JTextPane jtxtpix;
    private javax.swing.JLabel lblram;
    // End of variables declaration//GEN-END:variables
}
